import { ShortcutRecipe } from "@/types/shortcut";

/**
 * Convert a ShortcutRecipe to Markdown format
 */
export function formatRecipeAsMarkdown(recipe: ShortcutRecipe): string {
  const lines: string[] = [];

  // Title
  lines.push(`# ${recipe.title}\n`);

  // Summary
  lines.push(`## Summary\n`);
  lines.push(`${recipe.summary}\n`);

  // Prerequisites
  if (recipe.prerequisites && recipe.prerequisites.length > 0) {
    lines.push(`## Prerequisites\n`);
    recipe.prerequisites.forEach((prereq) => {
      lines.push(`- ${prereq}`);
    });
    lines.push("");
  }

  // Step-by-step instructions
  lines.push(`## Step-by-Step Build Instructions\n`);
  lines.push(`1. Open the **Shortcuts** app on your device`);
  lines.push(`2. Tap **+** (or click **New Shortcut** on Mac)`);
  lines.push(`3. Follow these steps to add each action:\n`);

  recipe.steps.forEach((step, index) => {
    lines.push(`### Step ${index + 1}: ${step.name}\n`);

    // Search hints
    if (step.searchHints.length > 0) {
      lines.push(`**How to find it:** Search for "${step.searchHints.join('" or "')}"\n`);
    }

    // Platform constraints
    if (step.platformConstraints && step.platformConstraints.length > 0) {
      lines.push(`**Platforms:** ${step.platformConstraints.join(", ")}\n`);
    }

    // Parameters
    if (step.parameters.length > 0) {
      lines.push(`**Parameters to configure:**\n`);
      step.parameters.forEach((param) => {
        lines.push(`- **${param.key}:** ${param.value}`);
        if (param.notes) {
          lines.push(`  - *${param.notes}*`);
        }
      });
      lines.push("");
    }

    // Warnings
    if (step.warnings && step.warnings.length > 0) {
      lines.push(`⚠️ **Warnings:**\n`);
      step.warnings.forEach((warning) => {
        lines.push(`- ${warning}`);
      });
      lines.push("");
    }
  });

  // Post-setup tests
  if (recipe.postSetupTests && recipe.postSetupTests.length > 0) {
    lines.push(`## Testing Your Shortcut\n`);
    recipe.postSetupTests.forEach((test, index) => {
      lines.push(`${index + 1}. ${test}`);
    });
    lines.push("");
  }

  lines.push(`---\n`);
  lines.push(`*Generated by Shortcut Maker*`);

  return lines.join("\n");
}

/**
 * Convert ShortcutRecipe to formatted step-by-step text
 */
export function formatRecipeAsText(recipe: ShortcutRecipe): string {
  const lines: string[] = [];

  lines.push(`${recipe.title}`);
  lines.push("=".repeat(recipe.title.length));
  lines.push("");
  lines.push(recipe.summary);
  lines.push("");

  if (recipe.prerequisites && recipe.prerequisites.length > 0) {
    lines.push("PREREQUISITES:");
    recipe.prerequisites.forEach((prereq, i) => {
      lines.push(`${i + 1}. ${prereq}`);
    });
    lines.push("");
  }

  lines.push("STEPS:");
  lines.push("");

  recipe.steps.forEach((step, index) => {
    lines.push(`${index + 1}. Add "${step.name}"`);
    if (step.searchHints.length > 0) {
      lines.push(`   Search: ${step.searchHints.join(", ")}`);
    }

    step.parameters.forEach((param) => {
      lines.push(`   - Set ${param.key} to: ${param.value}`);
      if (param.notes) {
        lines.push(`     (${param.notes})`);
      }
    });

    if (step.warnings && step.warnings.length > 0) {
      lines.push(`   ⚠️  ${step.warnings.join("; ")}`);
    }

    lines.push("");
  });

  if (recipe.postSetupTests && recipe.postSetupTests.length > 0) {
    lines.push("TESTING:");
    recipe.postSetupTests.forEach((test, i) => {
      lines.push(`${i + 1}. ${test}`);
    });
  }

  return lines.join("\n");
}
